# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_tsv": "02B_geolocation_profile.ipynb",
         "gzip_reading": "02B_geolocation_profile.ipynb",
         "school_plan__features": "01_features.ipynb",
         "translate_latlng": "01_features.ipynb",
         "kdtree_neighbors": "01_features.ipynb",
         "train_plan__latlng": "01_features.ipynb",
         "train_plan__nbusers": "01_features.ipynb",
         "train_time_features": "01_features.ipynb",
         "census_income_median": "01_features.ipynb",
         "census_income_avg": "01_features.ipynb",
         "gini_processing": "01_features.ipynb",
         "gini": "01_features.ipynb",
         "census_sentiment_analy": "01_features.ipynb",
         "convert_sent2score": "01_features.ipynb",
         "transform_churn_series": "01_features.ipynb",
         "classifier": "01_features.ipynb",
         "imp_mean": "02B_geolocation_profile.ipynb",
         "imp_med": "02B_geolocation_profile.ipynb",
         "load_directory_files_dict": "03A_churn_model.ipynb",
         "add_prefix_columns": "02A_user_profile.ipynb",
         "shorten_columns_str": "02A_user_profile.ipynb"}

modules = ["L0_exploration.py",
           "L1_features_gen.py",
           "L2A_user_model_explore.py",
           "L2B_geo_model_explore.py",
           "L3A_user_model.py"]

doc_url = "https://howt51.github.io/telco_churn_zig/"

git_url = "https://github.com/howt51/telco_churn_zig/tree/master/"

def custom_doc_links(name): return None
